=begin
	Rakefile to make the wire-server library and executable
=end

C_FLAGS = "-Werror -I."

EXEC 	= "./bin/wire.out"
LIB 	= "./lib/wire.a"

task :default => [:build]

header_files = %w(system-includes.h wire-server.h wire-listener.h api.h)
file_roots = %w(main wire-server wire-listener api)

file_roots.each do |element|
    file "obj/#{File.basename(element)}.o" => header_files + ["#{element}.c"] do
        puts "Compiling #{element}"
        fail unless system "cc #{C_FLAGS} -c #{element}.c -o obj/#{File.basename(element)}.o"
    end
end

obj_files = file_roots.map {|item| "obj/" + File.basename(item) + ".o"}

file "#{LIB}" =>  obj_files do
	puts "Creating #{LIB} lib"
	system "ar crs #{LIB} " + obj_files.join(" ") + "> /dev/null"
end

file "#{EXEC}" => "#{LIB}" do
	puts "Linking wire"
    system "cc -o #{EXEC} #{LIB}"
end

desc "Compiles and links the wire-server executable"
task :build => "#{EXEC}" do
	puts "#{EXEC} built."
end

desc "Removes artefacts"
task :clean do 
	system "rm -f obj/*"
	system "rm -f lib/*"
	system "rm -f bin/*"
end

desc "Runs the wire"
task :run => :build do 
	system "#{EXEC} 3901 1"
end
