=begin
	Rakefile to make the wire-server library and executable
=end

EXEC 	= "./bin/wire.out"
LIB 	= "./lib/wire.a"

task :default => [:build]

heads = %w(wire-server.h)
fileroots = %w(main wire-server)

fileroots.each do |element|
    file "obj/#{element}.o" => heads + ["#{element}.c"] do
        puts "Compiling #{element}"
        system "cc -c #{element}.c -o obj/#{element}.o"
    end
end

objfiles = fileroots.map {|item| "obj/" + item + ".o"}

file "#{LIB}" =>  objfiles do
	puts "Building library"
	system "ar rvs #{LIB} " + objfiles.join(" ") + "> /dev/null"
end

desc "Builds the listener executable"
file "#{EXEC}" => "#{LIB}" do
	puts "Linking"
    system "cc -o #{EXEC} #{LIB}"
end

desc "Compiles and links the wire-server executable"
task :build => "#{EXEC}" do
	puts "#{EXEC} is ready"
end

desc "Removes artefacts"
task :clean do 
	system "rm obj/* > /dev/null"
	system "rm lib/* > /dev/null"
	system "rm bin/* > /dev/null"
end

desc "Runs the server"
task :run do 
	system "#{EXEC} 3901"
end
